FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN yarn install

COPY tsconfig.json ./
COPY src ./src
COPY index.html ./

RUN yarn run build

FROM nginx:1.27-alpine

# Nginx の待機ポートを 80 から 8080 に書き換える
RUN sed -i 's/listen       80;/listen       8080;/g' /etc/nginx/conf.d/default.conf

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
