FROM node:20-alpine AS builder

WORKDIR /app
	RUN apk add --no-cache openssl

COPY package*.json ./
RUN npm install

COPY tsconfig.json ./
COPY src ./src
COPY prisma ./prisma

RUN npx prisma generate
RUN npm run build

FROM node:20-alpine

WORKDIR /app
	RUN apk add --no-cache openssl

COPY package*.json ./
RUN npm install --omit=dev

COPY --from=builder /app/dist ./dist
COPY prisma ./prisma

ENV NODE_ENV=production
# saas backend 用
EXPOSE 3201  

CMD ["node", "dist/index.js"]
