FROM node:20-alpine AS builder

WORKDIR /app

RUN apk add --no-cache openssl

COPY package*.json ./
RUN yarn install

COPY tsconfig.json ./
COPY src ./src
COPY prisma ./prisma

RUN npx prisma generate
RUN yarn run build

FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache openssl

COPY package*.json ./
RUN yarn install --production --frozen-lockfile

COPY --from=builder /app/dist ./dist
COPY prisma ./prisma

ENV NODE_ENV=production
# microservice1 用
EXPOSE 3101 

CMD ["node", "dist/index.js"]
